name: Remove Background

on: [workflow_dispatch]

jobs:
  remove-bg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run remove-bg
